### ISSUE TITLE
Game select OK button

### ISSUE THREAD

**Issue by PidgeonBrained** [PidgeonBrained/hidden_village_v0.6#3]
**Describe the issue**
Ok button on game select screen doesn't do anything. Pressing the button on the game is what selects it.

**Expected behavior**
Either select game before starting or get rid of button

**Screenshots**
![image](https://github.com/user-attachments/assets/f366bff7-6537-436b-9eee-9ae45f49b99e)

**Comment by YohannesAd** [comment]
implemented the OK button functionality to ensure the game only starts after selecting a conjecture and clicking OK. The selected conjecture is highlighted, and the OK button is disabled until a selection is made. Added feedback message for the selected conjecture. This resolves the issue where the game would start immediately upon selection without requiring the OK confirmation.
